### ISSUE TITLE
How to add OR relation between searched values

### ISSUE THREAD

**Issue by PriaBrock** [Padam87/SearchBundle#5]
Hi,
I would like to exchange your default AND relation between searched values for OR. Is it possible? I couldn't find this option in the documentation or in the code.

Thanks

**Comment by Padam87** [comment]
Hi @PriaBrock,

At the moment that is not possible, but it should be easy to implement. Do you want to give it a try?
I can propably do that later today, it would be a nice feature.

By the way, what is your use case? Initially I discarded the idea of having OR relations, because filter forms usually require ANDs.

**Comment by PriaBrock** [comment]
Hi @Padam87 ,

yes, sure, I will try it as soon as I'll finish this project. 

I'm using it  to search over my own repository with products and search for keywords in text descriptions (therefore I need the OR statement). So it's not exactly the filter functionality I'm using so as the search one.

**Comment by Padam87** [comment]
In that case, wouldn't it be easier to just use the doctrine query builder?

We have been using this bundle for more than 2 years, and it is mainly useful when the user submits a search form, and you cannot know which fields they would like to filter.

The feature request is totally valid though.
